
        self.AssetSQ_Frame = QtWidgets.QFrame(self.centralwidget)
        self.AssetSQ_Frame.setGeometry(QtCore.QRect(140, 30, 120, 120))
        self.AssetSQ_Frame.setAutoFillBackground(False)
        self.AssetSQ_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AssetSQ_Frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AssetSQ_Frame.setLineWidth(1)
        self.AssetSQ_Frame.setObjectName("AssetSQ_Frame")
        self.ASSQ_pushButtonB = QtWidgets.QPushButton(self.AssetSQ_Frame)
        self.ASSQ_pushButtonB.setGeometry(QtCore.QRect(98, 15, 18, 18))
        self.ASSQ_pushButtonB.setAutoFillBackground(False)
        self.ASSQ_pushButtonB.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_concept_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_concept_02.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_concept_01.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_concept_02.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.ASSQ_pushButtonB.setIcon(icon)
        self.ASSQ_pushButtonB.setIconSize(QtCore.QSize(18, 18))
        self.ASSQ_pushButtonB.setCheckable(True)
        self.ASSQ_pushButtonB.setFlat(True)
        self.ASSQ_pushButtonB.setObjectName("ASSQ_pushButtonB")
        self.ASSQ_pushButtonC = QtWidgets.QPushButton(self.AssetSQ_Frame)
        self.ASSQ_pushButtonC.setEnabled(True)
        self.ASSQ_pushButtonC.setGeometry(QtCore.QRect(98, 34, 18, 18))
        self.ASSQ_pushButtonC.setAutoFillBackground(False)
        self.ASSQ_pushButtonC.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_mod_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_mod_02.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_mod_01.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.ASSQ_pushButtonC.setIcon(icon1)
        self.ASSQ_pushButtonC.setIconSize(QtCore.QSize(18, 18))
        self.ASSQ_pushButtonC.setCheckable(True)
        self.ASSQ_pushButtonC.setFlat(True)
        self.ASSQ_pushButtonC.setObjectName("ASSQ_pushButtonC")
        self.ASSQ_pushButtonD = QtWidgets.QPushButton(self.AssetSQ_Frame)
        self.ASSQ_pushButtonD.setEnabled(True)
        self.ASSQ_pushButtonD.setGeometry(QtCore.QRect(98, 53, 18, 18))
        self.ASSQ_pushButtonD.setAutoFillBackground(False)
        self.ASSQ_pushButtonD.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Tex_02.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Tex_01.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Tex_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Tex_01.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Tex_02.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Tex_02.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.ASSQ_pushButtonD.setIcon(icon2)
        self.ASSQ_pushButtonD.setIconSize(QtCore.QSize(18, 18))
        self.ASSQ_pushButtonD.setCheckable(True)
        self.ASSQ_pushButtonD.setFlat(True)
        self.ASSQ_pushButtonD.setObjectName("ASSQ_pushButtonD")
        self.ASSQ_pushButtonE = QtWidgets.QPushButton(self.AssetSQ_Frame)
        self.ASSQ_pushButtonE.setGeometry(QtCore.QRect(98, 72, 18, 18))
        self.ASSQ_pushButtonE.setAutoFillBackground(False)
        self.ASSQ_pushButtonE.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Rig_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Rig_02.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Rig_02.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.ASSQ_pushButtonE.setIcon(icon3)
        self.ASSQ_pushButtonE.setIconSize(QtCore.QSize(18, 18))
        self.ASSQ_pushButtonE.setCheckable(True)
        self.ASSQ_pushButtonE.setFlat(True)
        self.ASSQ_pushButtonE.setObjectName("ASSQ_pushButtonE")
        self.ASSQ_pushButtonA = QtWidgets.QPushButton(self.AssetSQ_Frame)
        self.ASSQ_pushButtonA.setGeometry(QtCore.QRect(2, 2, 96, 96))
        self.ASSQ_pushButtonA.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/asset_cha_150.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ASSQ_pushButtonA.setIcon(icon4)
        self.ASSQ_pushButtonA.setIconSize(QtCore.QSize(96, 96))
        self.ASSQ_pushButtonA.setCheckable(True)
        self.ASSQ_pushButtonA.setFlat(True)
        self.ASSQ_pushButtonA.setObjectName("ASSQ_pushButtonA")
        self.ASSQ_LabelA = QtWidgets.QLabel(self.AssetSQ_Frame)
        self.ASSQ_LabelA.setGeometry(QtCore.QRect(2, 95, 114, 18))
        self.ASSQ_LabelA.setMinimumSize(QtCore.QSize(114, 18))
        self.ASSQ_LabelA.setMaximumSize(QtCore.QSize(114, 18))
        self.ASSQ_LabelA.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ASSQ_LabelA.setObjectName("ASSQ_LabelA")
        self.AssetLong_Frame = QtWidgets.QFrame(self.centralwidget)
        self.AssetLong_Frame.setGeometry(QtCore.QRect(140, 210, 561, 50))
        self.AssetLong_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AssetLong_Frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AssetLong_Frame.setLineWidth(0)
        self.AssetLong_Frame.setObjectName("AssetLong_Frame")
        self.ASL_buttonB1 = QtWidgets.QPushButton(self.AssetLong_Frame)
        self.ASL_buttonB1.setGeometry(QtCore.QRect(230, 20, 18, 18))
        self.ASL_buttonB1.setAutoFillBackground(False)
        self.ASL_buttonB1.setText("")
        self.ASL_buttonB1.setIcon(icon)
        self.ASL_buttonB1.setIconSize(QtCore.QSize(18, 18))
        self.ASL_buttonB1.setCheckable(True)
        self.ASL_buttonB1.setFlat(True)
        self.ASL_buttonB1.setObjectName("ASL_buttonB1")
        self.ASL_buttonB2 = QtWidgets.QPushButton(self.AssetLong_Frame)
        self.ASL_buttonB2.setEnabled(True)
        self.ASL_buttonB2.setGeometry(QtCore.QRect(250, 20, 18, 18))
        self.ASL_buttonB2.setAutoFillBackground(False)
        self.ASL_buttonB2.setText("")
        self.ASL_buttonB2.setIcon(icon1)
        self.ASL_buttonB2.setIconSize(QtCore.QSize(18, 18))
        self.ASL_buttonB2.setCheckable(True)
        self.ASL_buttonB2.setFlat(True)
        self.ASL_buttonB2.setObjectName("ASL_buttonB2")
        self.ASL_buttonB3 = QtWidgets.QPushButton(self.AssetLong_Frame)
        self.ASL_buttonB3.setEnabled(True)
        self.ASL_buttonB3.setGeometry(QtCore.QRect(270, 20, 18, 18))
        self.ASL_buttonB3.setAutoFillBackground(False)
        self.ASL_buttonB3.setText("")
        self.ASL_buttonB3.setIcon(icon2)
        self.ASL_buttonB3.setIconSize(QtCore.QSize(18, 18))
        self.ASL_buttonB3.setCheckable(True)
        self.ASL_buttonB3.setFlat(True)
        self.ASL_buttonB3.setObjectName("ASL_buttonB3")
        self.ASL_buttonB4 = QtWidgets.QPushButton(self.AssetLong_Frame)
        self.ASL_buttonB4.setGeometry(QtCore.QRect(290, 20, 18, 18))
        self.ASL_buttonB4.setAutoFillBackground(False)
        self.ASL_buttonB4.setText("")
        self.ASL_buttonB4.setIcon(icon3)
        self.ASL_buttonB4.setIconSize(QtCore.QSize(18, 18))
        self.ASL_buttonB4.setCheckable(True)
        self.ASL_buttonB4.setFlat(True)
        self.ASL_buttonB4.setObjectName("ASL_buttonB4")
        self.ASL_buttonC = QtWidgets.QPushButton(self.AssetLong_Frame)
        self.ASL_buttonC.setGeometry(QtCore.QRect(350, 0, 150, 50))
        self.ASL_buttonC.setAutoFillBackground(False)
        self.ASL_buttonC.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/userBlockB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/userBlockB_check.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon5.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/userBlockB_check.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon5.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/userBlockB_check.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.ASL_buttonC.setIcon(icon5)
        self.ASL_buttonC.setIconSize(QtCore.QSize(150, 50))
        self.ASL_buttonC.setCheckable(True)
        self.ASL_buttonC.setFlat(True)
        self.ASL_buttonC.setObjectName("ASL_buttonC")
        self.ASL_labelB = QtWidgets.QLabel(self.AssetLong_Frame)
        self.ASL_labelB.setGeometry(QtCore.QRect(362, 20, 130, 16))
        self.ASL_labelB.setMinimumSize(QtCore.QSize(130, 16))
        self.ASL_labelB.setMaximumSize(QtCore.QSize(130, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.ASL_labelB.setFont(font)
        self.ASL_labelB.setAlignment(QtCore.Qt.AlignCenter)
        self.ASL_labelB.setObjectName("ASL_labelB")
        self.ASL_buttonA = QtWidgets.QPushButton(self.AssetLong_Frame)
        self.ASL_buttonA.setGeometry(QtCore.QRect(0, 0, 50, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.ASL_buttonA.setPalette(palette)
        self.ASL_buttonA.setAutoFillBackground(False)
        self.ASL_buttonA.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block_Check.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block_Check.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block_Check.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.ASL_buttonA.setIcon(icon6)
        self.ASL_buttonA.setIconSize(QtCore.QSize(50, 50))
        self.ASL_buttonA.setCheckable(True)
        self.ASL_buttonA.setFlat(True)
        self.ASL_buttonA.setObjectName("ASL_buttonA")
        self.ASL_buttonD1 = QtWidgets.QPushButton(self.AssetLong_Frame)
        self.ASL_buttonD1.setEnabled(False)
        self.ASL_buttonD1.setGeometry(QtCore.QRect(500, 2, 23, 23))
        self.ASL_buttonD1.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block_B.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ASL_buttonD1.setIcon(icon7)
        self.ASL_buttonD1.setIconSize(QtCore.QSize(23, 28))
        self.ASL_buttonD1.setCheckable(True)
        self.ASL_buttonD1.setFlat(True)
        self.ASL_buttonD1.setObjectName("ASL_buttonD1")
        self.ASL_buttonD2 = QtWidgets.QPushButton(self.AssetLong_Frame)
        self.ASL_buttonD2.setEnabled(False)
        self.ASL_buttonD2.setGeometry(QtCore.QRect(523, 2, 23, 23))
        self.ASL_buttonD2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block_C.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ASL_buttonD2.setIcon(icon8)
        self.ASL_buttonD2.setIconSize(QtCore.QSize(23, 28))
        self.ASL_buttonD2.setCheckable(True)
        self.ASL_buttonD2.setFlat(True)
        self.ASL_buttonD2.setObjectName("ASL_buttonD2")
        self.ASL_buttonD3 = QtWidgets.QPushButton(self.AssetLong_Frame)
        self.ASL_buttonD3.setEnabled(False)
        self.ASL_buttonD3.setGeometry(QtCore.QRect(500, 25, 23, 23))
        self.ASL_buttonD3.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/userBlockE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block_D.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ASL_buttonD4.setIcon(icon10)
        self.ASL_buttonD4.setIconSize(QtCore.QSize(23, 28))
        self.ASL_buttonD4.setCheckable(True)
        self.ASL_buttonD4.setFlat(True)
        self.ASL_buttonD4.setObjectName("ASL_buttonD4")
        self.label = QtWidgets.QLabel(self.AssetLong_Frame)
        self.label.setGeometry(QtCore.QRect(50, 0, 300, 50))
        self.label.setMaximumSize(QtCore.QSize(300, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/assetLong_A01.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.AssetLong_Frame)
        self.label_2.setGeometry(QtCore.QRect(66, 20, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.AssetSQ_FrameSmall = QtWidgets.QFrame(self.centralwidget)
        self.AssetSQ_FrameSmall.setGeometry(QtCore.QRect(130, 300, 550, 30))
        self.AssetSQ_FrameSmall.setMaximumSize(QtCore.QSize(550, 30))
        self.AssetSQ_FrameSmall.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AssetSQ_FrameSmall.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AssetSQ_FrameSmall.setObjectName("AssetSQ_FrameSmall")
        self.ASLS_labelA = QtWidgets.QLabel(self.AssetSQ_FrameSmall)
        self.ASLS_labelA.setGeometry(QtCore.QRect(27, 2, 225, 25))
        self.ASLS_labelA.setMinimumSize(QtCore.QSize(200, 25))
        self.ASLS_labelA.setMaximumSize(QtCore.QSize(400, 25))
        self.ASLS_labelA.setText("")
        self.ASLS_labelA.setPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/assetLong_A01.png"))
        self.ASLS_labelA.setScaledContents(True)
        self.ASLS_labelA.setObjectName("ASLS_labelA")
        self.ASLS_buttonM = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonM.setEnabled(True)
        self.ASLS_buttonM.setGeometry(QtCore.QRect(276, 4, 22, 22))
        self.ASLS_buttonM.setMaximumSize(QtCore.QSize(22, 22))
        self.ASLS_buttonM.setAutoFillBackground(False)
        self.ASLS_buttonM.setText("")
        self.ASLS_buttonM.setIcon(icon1)
        self.ASLS_buttonM.setIconSize(QtCore.QSize(22, 22))
        self.ASLS_buttonM.setCheckable(True)
        self.ASLS_buttonM.setFlat(True)
        self.ASLS_buttonM.setObjectName("ASLS_buttonM")
        self.ASLS_buttonC = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonC.setGeometry(QtCore.QRect(252, 4, 22, 22))
        self.ASLS_buttonC.setMaximumSize(QtCore.QSize(22, 22))
        self.ASLS_buttonC.setAutoFillBackground(False)
        self.ASLS_buttonC.setText("")
        self.ASLS_buttonC.setIcon(icon)
        self.ASLS_buttonC.setIconSize(QtCore.QSize(22, 22))
        self.ASLS_buttonC.setCheckable(True)
        self.ASLS_buttonC.setFlat(True)
        self.ASLS_buttonC.setObjectName("ASLS_buttonC")
        self.ASLS_buttonT = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonT.setEnabled(True)
        self.ASLS_buttonT.setGeometry(QtCore.QRect(300, 4, 22, 22))
        self.ASLS_buttonT.setMaximumSize(QtCore.QSize(22, 22))
        self.ASLS_buttonT.setAutoFillBackground(False)
        self.ASLS_buttonT.setText("")
        self.ASLS_buttonT.setIcon(icon2)
        self.ASLS_buttonT.setIconSize(QtCore.QSize(22, 22))
        self.ASLS_buttonT.setCheckable(True)
        self.ASLS_buttonT.setFlat(True)
        self.ASLS_buttonT.setObjectName("ASLS_buttonT")
        self.ASLS_buttonR = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonR.setGeometry(QtCore.QRect(324, 4, 22, 22))
        self.ASLS_buttonR.setMaximumSize(QtCore.QSize(22, 22))
        self.ASLS_buttonR.setAutoFillBackground(False)
        self.ASLS_buttonR.setText("")
        self.ASLS_buttonR.setIcon(icon3)
        self.ASLS_buttonR.setIconSize(QtCore.QSize(22, 22))
        self.ASLS_buttonR.setCheckable(True)
        self.ASLS_buttonR.setFlat(True)
        self.ASLS_buttonR.setObjectName("ASLS_buttonR")
        self.ASLS_labelB = QtWidgets.QLabel(self.AssetSQ_FrameSmall)
        self.ASLS_labelB.setGeometry(QtCore.QRect(346, 2, 100, 25))
        self.ASLS_labelB.setMinimumSize(QtCore.QSize(100, 15))
        self.ASLS_labelB.setMaximumSize(QtCore.QSize(200, 25))
        self.ASLS_labelB.setText("")
        self.ASLS_labelB.setPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/userBlockB.png"))
        self.ASLS_labelB.setScaledContents(True)
        self.ASLS_labelB.setObjectName("ASLS_labelB")
        self.ASLS_textA = QtWidgets.QLabel(self.AssetSQ_FrameSmall)
        self.ASLS_textA.setGeometry(QtCore.QRect(38, 8, 200, 14))
        self.ASLS_textA.setMaximumSize(QtCore.QSize(200, 14))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(76, 85, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 85, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.ASLS_textA.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.ASLS_textA.setFont(font)
        self.ASLS_textA.setObjectName("ASLS_textA")
        self.ASLS_textB = QtWidgets.QLabel(self.AssetSQ_FrameSmall)
        self.ASLS_textB.setGeometry(QtCore.QRect(360, 8, 81, 14))
        self.ASLS_textB.setMaximumSize(QtCore.QSize(100, 14))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(76, 85, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 85, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ASLS_textB.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.ASLS_textB.setFont(font)
        self.ASLS_textB.setObjectName("ASLS_textB")
        self.ASLS_buttonA = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonA.setGeometry(QtCore.QRect(2, 2, 25, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.ASLS_buttonA.setPalette(palette)
        self.ASLS_buttonA.setAutoFillBackground(False)
        self.ASLS_buttonA.setText("")
        self.ASLS_buttonA.setIcon(icon6)
        self.ASLS_buttonA.setIconSize(QtCore.QSize(25, 25))
        self.ASLS_buttonA.setCheckable(True)
        self.ASLS_buttonA.setFlat(True)
        self.ASLS_buttonA.setObjectName("ASLS_buttonA")
        self.ASLS_button_stateA = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_button_stateA.setEnabled(False)
        self.ASLS_button_stateA.setGeometry(QtCore.QRect(445, 3, 23, 23))
        self.ASLS_button_stateA.setText("")
        self.ASLS_button_stateA.setIcon(icon7)
        self.ASLS_button_stateA.setIconSize(QtCore.QSize(23, 28))
        self.ASLS_button_stateA.setCheckable(True)
        self.ASLS_button_stateA.setFlat(True)
        self.ASLS_button_stateA.setObjectName("ASLS_button_stateA")
        self.ASLS_button_stateB = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_button_stateB.setEnabled(False)
        self.ASLS_button_stateB.setGeometry(QtCore.QRect(467, 3, 23, 23))
        self.ASLS_button_stateB.setText("")
        self.ASLS_button_stateB.setIcon(icon8)
        self.ASLS_button_stateB.setIconSize(QtCore.QSize(23, 28))
        self.ASLS_button_stateB.setCheckable(True)
        self.ASLS_button_stateB.setFlat(True)
        self.ASLS_button_stateB.setObjectName("ASLS_button_stateB")
        self.ASLS_button_stateC = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_button_stateC.setEnabled(False)
        self.ASLS_button_stateC.setGeometry(QtCore.QRect(489, 3, 23, 23))
        self.ASLS_button_stateC.setText("")
        self.ASLS_button_stateC.setIcon(icon9)
        self.ASLS_button_stateC.setIconSize(QtCore.QSize(23, 28))
        self.ASLS_button_stateC.setCheckable(True)
        self.ASLS_button_stateC.setFlat(True)
        self.ASLS_button_stateC.setObjectName("ASLS_button_stateC")
        self.ASLS_button_stateD = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_button_stateD.setEnabled(False)
        self.ASLS_button_stateD.setGeometry(QtCore.QRect(511, 3, 23, 23))
        self.ASLS_button_stateD.setText("")
        self.ASLS_button_stateD.setIcon(icon10)
        self.ASLS_button_stateD.setIconSize(QtCore.QSize(23, 28))
        self.ASLS_button_stateD.setCheckable(True)
        self.ASLS_button_stateD.setFlat(True)
        self.ASLS_button_stateD.setObjectName("ASLS_button_stateD")
        MainWindow.setCentralWidget(self.centralwidget)

        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.ASSQ_LabelA.setText(QtWidgets.QApplication.translate("MainWindow", "Asset Name", None, -1))
        self.ASL_labelB.setText(QtWidgets.QApplication.translate("MainWindow", "User Name", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "AssetName:", None, -1))
        self.ASLS_textA.setText(QtWidgets.QApplication.translate("MainWindow", "AssetName", None, -1))
        self.ASLS_textB.setText(QtWidgets.QApplication.translate("MainWindow", "User", None, -1))


 