# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/alphaOnly/github/pipelineTool/UI_code/nameCard.ui'
#
# Created: Thu Dec 14 13:55:49 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NameCard_frame = QtWidgets.QFrame(self.centralwidget)
        self.NameCard_frame.setGeometry(QtCore.QRect(200, 120, 300, 100))
        self.NameCard_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NameCard_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NameCard_frame.setObjectName("NameCard_frame")
        self.NC_BGImageLabelA = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_BGImageLabelA.setGeometry(QtCore.QRect(0, 0, 300, 100))
        self.NC_BGImageLabelA.setText("")
        self.NC_BGImageLabelA.setPixmap(QtGui.QPixmap("../UI/colorTemplate_A001.png"))
        self.NC_BGImageLabelA.setScaledContents(True)
        self.NC_BGImageLabelA.setObjectName("NC_BGImageLabelA")
        self.NC_buttonA = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonA.setGeometry(QtCore.QRect(0, 0, 12, 25))
        self.NC_buttonA.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../UI/colorTemplate_C001.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NC_buttonA.setIcon(icon)
        self.NC_buttonA.setIconSize(QtCore.QSize(25, 25))
        self.NC_buttonA.setFlat(False)
        self.NC_buttonA.setObjectName("NC_buttonA")
        self.NC_buttonB = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonB.setGeometry(QtCore.QRect(0, 25, 12, 25))
        self.NC_buttonB.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../UI/colorTemplate_C002.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NC_buttonB.setIcon(icon1)
        self.NC_buttonB.setIconSize(QtCore.QSize(25, 25))
        self.NC_buttonB.setFlat(False)
        self.NC_buttonB.setObjectName("NC_buttonB")
        self.NC_buttonC = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonC.setGeometry(QtCore.QRect(0, 50, 12, 25))
        self.NC_buttonC.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../UI/colorTemplate_C003.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NC_buttonC.setIcon(icon2)
        self.NC_buttonC.setIconSize(QtCore.QSize(25, 25))
        self.NC_buttonC.setFlat(False)
        self.NC_buttonC.setObjectName("NC_buttonC")
        self.NC_buttonD = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonD.setGeometry(QtCore.QRect(0, 75, 12, 25))
        self.NC_buttonD.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../UI/colorTemplate_C004.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NC_buttonD.setIcon(icon3)
        self.NC_buttonD.setIconSize(QtCore.QSize(25, 25))
        self.NC_buttonD.setFlat(False)
        self.NC_buttonD.setObjectName("NC_buttonD")
        self.NC_BGImageLabelB = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_BGImageLabelB.setGeometry(QtCore.QRect(12, 1, 96, 96))
        self.NC_BGImageLabelB.setText("")
        self.NC_BGImageLabelB.setPixmap(QtGui.QPixmap("../UI/colorTemplate_A002.png"))
        self.NC_BGImageLabelB.setScaledContents(True)
        self.NC_BGImageLabelB.setObjectName("NC_BGImageLabelB")
        self.NC_InfoTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_InfoTextLabel.setGeometry(QtCore.QRect(120, 1, 61, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_InfoTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_InfoTextLabel.setFont(font)
        self.NC_InfoTextLabel.setObjectName("NC_InfoTextLabel")
        self.NC_NameTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_NameTextLabel.setGeometry(QtCore.QRect(120, 20, 61, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_NameTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_NameTextLabel.setFont(font)
        self.NC_NameTextLabel.setObjectName("NC_NameTextLabel")
        self.NC_DeptTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_DeptTextLabel.setGeometry(QtCore.QRect(125, 40, 27, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_DeptTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_DeptTextLabel.setFont(font)
        self.NC_DeptTextLabel.setObjectName("NC_DeptTextLabel")
        self.NC_SecTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_SecTextLabel.setGeometry(QtCore.QRect(200, 40, 25, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_SecTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_SecTextLabel.setFont(font)
        self.NC_SecTextLabel.setObjectName("NC_SecTextLabel")
        self.NC_specATextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_specATextLabel.setGeometry(QtCore.QRect(125, 60, 150, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_specATextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_specATextLabel.setFont(font)
        self.NC_specATextLabel.setObjectName("NC_specATextLabel")
        self.NC_specBTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_specBTextLabel.setGeometry(QtCore.QRect(125, 80, 150, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_specBTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_specBTextLabel.setFont(font)
        self.NC_specBTextLabel.setObjectName("NC_specBTextLabel")
        self.NC_DeptValueTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_DeptValueTextLabel.setGeometry(QtCore.QRect(158, 40, 40, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_DeptValueTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_DeptValueTextLabel.setFont(font)
        self.NC_DeptValueTextLabel.setObjectName("NC_DeptValueTextLabel")
        self.NC_SecValueTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_SecValueTextLabel.setGeometry(QtCore.QRect(225, 40, 50, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_SecValueTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_SecValueTextLabel.setFont(font)
        self.NC_SecValueTextLabel.setObjectName("NC_SecValueTextLabel")
        self.NC_buttonE = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonE.setGeometry(QtCore.QRect(13, 1, 100, 98))
        self.NC_buttonE.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../UI/noImage_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NC_buttonE.setIcon(icon4)
        self.NC_buttonE.setIconSize(QtCore.QSize(100, 100))
        self.NC_buttonE.setFlat(True)
        self.NC_buttonE.setObjectName("NC_buttonE")
        self.NC_buttonG = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonG.setGeometry(QtCore.QRect(284, 1, 15, 15))
        self.NC_buttonG.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../UI/sub_002.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NC_buttonG.setIcon(icon5)
        self.NC_buttonG.setIconSize(QtCore.QSize(15, 15))
        self.NC_buttonG.setFlat(True)
        self.NC_buttonG.setObjectName("NC_buttonG")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.NC_InfoTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", "INFO :", None, -1))
        self.NC_NameTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Name", None, -1))
        self.NC_DeptTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", "DEPT.", None, -1))
        self.NC_SecTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", "SEC.", None, -1))
        self.NC_specATextLabel.setText(QtWidgets.QApplication.translate("MainWindow", "SpecialA", None, -1))
        self.NC_specBTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", "SpecialB", None, -1))
        self.NC_DeptValueTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", "DEPT.", None, -1))
        self.NC_SecValueTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", "DEPT.", None, -1))




class mod_MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
   
    def __init__(self, parent= QtWidgets.QApplication.activeWindow()):
        super(mod_MainWindow, self).__init__(parent)
        #self.QTITEM.ACTION.connect(self.MODDEF)
        self.setupUi(self)
    #def self.MODDEF(self):



def main():
    global ui
    app = QtWidgets.QApplication.instance()
    if app == None: app = QtWidgets.QApplication(sys.argv)
    try:
        ui.close()
        ui.deleteLater()
    except: pass
    ui = mod_MainWindow()
    ui.show()
 
if __name__ == '__main__':
    main()


 