# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/alphaOnly/github/pipelineTool/UI_code/test_UI.ui'
#
# Created: Mon Dec 18 15:10:30 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AssetSQ_FrameSmall = QtWidgets.QFrame(self.centralwidget)
        self.AssetSQ_FrameSmall.setGeometry(QtCore.QRect(100, 160, 550, 30))
        self.AssetSQ_FrameSmall.setMaximumSize(QtCore.QSize(550, 30))
        self.AssetSQ_FrameSmall.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AssetSQ_FrameSmall.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AssetSQ_FrameSmall.setObjectName("AssetSQ_FrameSmall")
        self.ASLS_labelA = QtWidgets.QLabel(self.AssetSQ_FrameSmall)
        self.ASLS_labelA.setGeometry(QtCore.QRect(27, 2, 225, 25))
        self.ASLS_labelA.setMinimumSize(QtCore.QSize(200, 25))
        self.ASLS_labelA.setMaximumSize(QtCore.QSize(400, 25))
        self.ASLS_labelA.setText("")
        self.ASLS_labelA.setPixmap(QtGui.QPixmap("../UI/assetLong_A01.png"))
        self.ASLS_labelA.setScaledContents(True)
        self.ASLS_labelA.setObjectName("ASLS_labelA")
        self.ASLS_buttonM = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonM.setEnabled(True)
        self.ASLS_buttonM.setGeometry(QtCore.QRect(276, 4, 22, 22))
        self.ASLS_buttonM.setMaximumSize(QtCore.QSize(22, 22))
        self.ASLS_buttonM.setAutoFillBackground(False)
        self.ASLS_buttonM.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../UI/button_Asset_mod_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../UI/button_Asset_mod_02.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("../UI/button_Asset_mod_01.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.ASLS_buttonM.setIcon(icon)
        self.ASLS_buttonM.setIconSize(QtCore.QSize(22, 22))
        self.ASLS_buttonM.setCheckable(True)
        self.ASLS_buttonM.setFlat(True)
        self.ASLS_buttonM.setObjectName("ASLS_buttonM")
        self.ASLS_buttonC = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonC.setGeometry(QtCore.QRect(252, 4, 22, 22))
        self.ASLS_buttonC.setMaximumSize(QtCore.QSize(22, 22))
        self.ASLS_buttonC.setAutoFillBackground(False)
        self.ASLS_buttonC.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../UI/button_Asset_concept_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("../UI/button_Asset_concept_02.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("../UI/button_Asset_concept_01.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("../UI/button_Asset_concept_02.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.ASLS_buttonC.setIcon(icon1)
        self.ASLS_buttonC.setIconSize(QtCore.QSize(22, 22))
        self.ASLS_buttonC.setCheckable(True)
        self.ASLS_buttonC.setFlat(True)
        self.ASLS_buttonC.setObjectName("ASLS_buttonC")
        self.ASLS_buttonT = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonT.setEnabled(True)
        self.ASLS_buttonT.setGeometry(QtCore.QRect(300, 4, 22, 22))
        self.ASLS_buttonT.setMaximumSize(QtCore.QSize(22, 22))
        self.ASLS_buttonT.setAutoFillBackground(False)
        self.ASLS_buttonT.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../UI/button_Asset_Tex_02.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap("../UI/button_Asset_Tex_01.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("../UI/button_Asset_Tex_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("../UI/button_Asset_Tex_01.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("../UI/button_Asset_Tex_02.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap("../UI/button_Asset_Tex_02.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.ASLS_buttonT.setIcon(icon2)
        self.ASLS_buttonT.setIconSize(QtCore.QSize(22, 22))
        self.ASLS_buttonT.setCheckable(True)
        self.ASLS_buttonT.setFlat(True)
        self.ASLS_buttonT.setObjectName("ASLS_buttonT")
        self.ASLS_buttonR = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonR.setGeometry(QtCore.QRect(324, 4, 22, 22))
        self.ASLS_buttonR.setMaximumSize(QtCore.QSize(22, 22))
        self.ASLS_buttonR.setAutoFillBackground(False)
        self.ASLS_buttonR.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../UI/button_Asset_Rig_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("../UI/button_Asset_Rig_02.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap("../UI/button_Asset_Rig_02.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.ASLS_buttonR.setIcon(icon3)
        self.ASLS_buttonR.setIconSize(QtCore.QSize(22, 22))
        self.ASLS_buttonR.setCheckable(True)
        self.ASLS_buttonR.setFlat(True)
        self.ASLS_buttonR.setObjectName("ASLS_buttonR")
        self.ASLS_labelB = QtWidgets.QLabel(self.AssetSQ_FrameSmall)
        self.ASLS_labelB.setGeometry(QtCore.QRect(346, 2, 100, 25))
        self.ASLS_labelB.setMinimumSize(QtCore.QSize(100, 15))
        self.ASLS_labelB.setMaximumSize(QtCore.QSize(200, 25))
        self.ASLS_labelB.setText("")
        self.ASLS_labelB.setPixmap(QtGui.QPixmap("../UI/userBlockB.png"))
        self.ASLS_labelB.setScaledContents(True)
        self.ASLS_labelB.setObjectName("ASLS_labelB")
        self.ASLS_textA = QtWidgets.QLabel(self.AssetSQ_FrameSmall)
        self.ASLS_textA.setGeometry(QtCore.QRect(38, 8, 200, 14))
        self.ASLS_textA.setMaximumSize(QtCore.QSize(200, 14))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.ASLS_textA.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.ASLS_textA.setFont(font)
        self.ASLS_textA.setObjectName("ASLS_textA")
        self.ASLS_textB = QtWidgets.QLabel(self.AssetSQ_FrameSmall)
        self.ASLS_textB.setGeometry(QtCore.QRect(360, 8, 81, 14))
        self.ASLS_textB.setMaximumSize(QtCore.QSize(100, 14))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.ASLS_textB.setFont(font)
        self.ASLS_textB.setObjectName("ASLS_textB")
        self.ASLS_buttonA = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonA.setGeometry(QtCore.QRect(2, 2, 25, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.ASLS_buttonA.setPalette(palette)
        self.ASLS_buttonA.setAutoFillBackground(False)
        self.ASLS_buttonA.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../UI/user_block_Check.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap("../UI/user_block.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("../UI/user_block.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("../UI/user_block.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("../UI/user_block_Check.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap("../UI/user_block_Check.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.ASLS_buttonA.setIcon(icon4)
        self.ASLS_buttonA.setIconSize(QtCore.QSize(25, 25))
        self.ASLS_buttonA.setCheckable(True)
        self.ASLS_buttonA.setFlat(True)
        self.ASLS_buttonA.setObjectName("ASLS_buttonA")
        self.ASLS_button_stateA = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_button_stateA.setEnabled(False)
        self.ASLS_button_stateA.setGeometry(QtCore.QRect(445, 3, 23, 23))
        self.ASLS_button_stateA.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../UI/user_block_B.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ASLS_button_stateA.setIcon(icon5)
        self.ASLS_button_stateA.setIconSize(QtCore.QSize(23, 28))
        self.ASLS_button_stateA.setCheckable(True)
        self.ASLS_button_stateA.setFlat(True)
        self.ASLS_button_stateA.setObjectName("ASLS_button_stateA")
        self.ASLS_button_stateB = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_button_stateB.setEnabled(False)
        self.ASLS_button_stateB.setGeometry(QtCore.QRect(467, 3, 23, 23))
        self.ASLS_button_stateB.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../UI/user_block_C.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ASLS_button_stateB.setIcon(icon6)
        self.ASLS_button_stateB.setIconSize(QtCore.QSize(23, 28))
        self.ASLS_button_stateB.setCheckable(True)
        self.ASLS_button_stateB.setFlat(True)
        self.ASLS_button_stateB.setObjectName("ASLS_button_stateB")
        self.ASLS_button_stateC = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_button_stateC.setEnabled(False)
        self.ASLS_button_stateC.setGeometry(QtCore.QRect(489, 3, 23, 23))
        self.ASLS_button_stateC.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../UI/userBlockE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ASLS_button_stateC.setIcon(icon7)
        self.ASLS_button_stateC.setIconSize(QtCore.QSize(23, 28))
        self.ASLS_button_stateC.setCheckable(True)
        self.ASLS_button_stateC.setFlat(True)
        self.ASLS_button_stateC.setObjectName("ASLS_button_stateC")
        self.ASLS_button_stateD = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_button_stateD.setEnabled(False)
        self.ASLS_button_stateD.setGeometry(QtCore.QRect(511, 3, 23, 23))
        self.ASLS_button_stateD.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../UI/user_block_D.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ASLS_button_stateD.setIcon(icon8)
        self.ASLS_button_stateD.setIconSize(QtCore.QSize(23, 28))
        self.ASLS_button_stateD.setCheckable(True)
        self.ASLS_button_stateD.setFlat(True)
        self.ASLS_button_stateD.setObjectName("ASLS_button_stateD")
        self.ASLS_textA_2 = QtWidgets.QLabel(self.centralwidget)
        self.ASLS_textA_2.setGeometry(QtCore.QRect(400, 340, 200, 14))
        self.ASLS_textA_2.setMaximumSize(QtCore.QSize(200, 14))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.ASLS_textA_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.ASLS_textA_2.setFont(font)
        self.ASLS_textA_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.ASLS_textA_2.setTextFormat(QtCore.Qt.PlainText)
        self.ASLS_textA_2.setObjectName("ASLS_textA_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.ASLS_textA.setText(QtWidgets.QApplication.translate("MainWindow", "AssetName", None, -1))
        self.ASLS_textB.setText(QtWidgets.QApplication.translate("MainWindow", "User", None, -1))
        self.ASLS_textA_2.setText(QtWidgets.QApplication.translate("MainWindow", "AssetName", None, -1))




class mod_MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
   
    def __init__(self, parent= QtWidgets.QApplication.activeWindow()):
        super(mod_MainWindow, self).__init__(parent)
        #self.QTITEM.ACTION.connect(self.MODDEF)
        self.setupUi(self)
    #def self.MODDEF(self):



def main():
    global ui
    app = QtWidgets.QApplication.instance()
    if app == None: app = QtWidgets.QApplication(sys.argv)
    try:
        ui.close()
        ui.deleteLater()
    except: pass
    ui = mod_MainWindow()
    ui.show()
 
if __name__ == '__main__':
    main()


 