# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/alphaOnly/github/mayaTool/keyFrameTools/UI/ui01.ui'
#
# Created: Fri May 04 18:23:09 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 891)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_numberJoints = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_numberJoints.setGeometry(QtCore.QRect(40, 80, 41, 25))
        self.lineEdit_numberJoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_numberJoints.setObjectName("lineEdit_numberJoints")
        self.label_sf = QtWidgets.QLabel(self.centralwidget)
        self.label_sf.setGeometry(QtCore.QRect(20, 20, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_sf.setFont(font)
        self.label_sf.setObjectName("label_sf")
        self.label_ef = QtWidgets.QLabel(self.centralwidget)
        self.label_ef.setGeometry(QtCore.QRect(40, 45, 71, 25))
        self.label_ef.setObjectName("label_ef")
        self.pushButton_createJoint = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_createJoint.setGeometry(QtCore.QRect(350, 80, 75, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.pushButton_createJoint.setFont(font)
        self.pushButton_createJoint.setObjectName("pushButton_createJoint")
        self.label_rt_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_rt_2.setGeometry(QtCore.QRect(220, 333, 71, 25))
        self.label_rt_2.setObjectName("label_rt_2")
        self.lineEdit_offsetFrame = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_offsetFrame.setGeometry(QtCore.QRect(220, 360, 61, 25))
        self.lineEdit_offsetFrame.setObjectName("lineEdit_offsetFrame")
        self.pushButton_makeOffsetFrame = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_makeOffsetFrame.setGeometry(QtCore.QRect(317, 360, 91, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.pushButton_makeOffsetFrame.setFont(font)
        self.pushButton_makeOffsetFrame.setObjectName("pushButton_makeOffsetFrame")
        self.lineEdit_offfsetStartFrame = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_offfsetStartFrame.setGeometry(QtCore.QRect(47, 360, 61, 25))
        self.lineEdit_offfsetStartFrame.setObjectName("lineEdit_offfsetStartFrame")
        self.label_sf_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_sf_2.setGeometry(QtCore.QRect(47, 333, 71, 25))
        self.label_sf_2.setObjectName("label_sf_2")
        self.label_ef_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ef_2.setGeometry(QtCore.QRect(127, 333, 71, 25))
        self.label_ef_2.setObjectName("label_ef_2")
        self.lineEdit_offfsetendFrame = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_offfsetendFrame.setGeometry(QtCore.QRect(127, 360, 61, 25))
        self.lineEdit_offfsetendFrame.setObjectName("lineEdit_offfsetendFrame")
        self.label_sf_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_sf_3.setGeometry(QtCore.QRect(47, 159, 81, 25))
        self.label_sf_3.setObjectName("label_sf_3")
        self.lineEdit_cutkeyFrames = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_cutkeyFrames.setGeometry(QtCore.QRect(47, 186, 61, 25))
        self.lineEdit_cutkeyFrames.setObjectName("lineEdit_cutkeyFrames")
        self.pushButton_cutKeys = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cutKeys.setGeometry(QtCore.QRect(127, 186, 91, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.pushButton_cutKeys.setFont(font)
        self.pushButton_cutKeys.setObjectName("pushButton_cutKeys")
        self.lineEdit_alignKey = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_alignKey.setGeometry(QtCore.QRect(47, 276, 61, 25))
        self.lineEdit_alignKey.setObjectName("lineEdit_alignKey")
        self.pushButton_alignKey = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_alignKey.setGeometry(QtCore.QRect(127, 276, 91, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.pushButton_alignKey.setFont(font)
        self.pushButton_alignKey.setObjectName("pushButton_alignKey")
        self.label_sf_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_sf_4.setGeometry(QtCore.QRect(47, 251, 81, 25))
        self.label_sf_4.setObjectName("label_sf_4")
        self.checkBox_offsetRandom = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_offsetRandom.setGeometry(QtCore.QRect(137, 313, 73, 25))
        self.checkBox_offsetRandom.setObjectName("checkBox_offsetRandom")
        self.lineEdit_modifyValue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_modifyValue.setGeometry(QtCore.QRect(30, 600, 91, 25))
        self.lineEdit_modifyValue.setObjectName("lineEdit_modifyValue")
        self.pushButton_makdModify = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_makdModify.setGeometry(QtCore.QRect(320, 600, 91, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.pushButton_makdModify.setFont(font)
        self.pushButton_makdModify.setObjectName("pushButton_makdModify")
        self.label_sf_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_sf_5.setGeometry(QtCore.QRect(30, 580, 101, 16))
        self.label_sf_5.setObjectName("label_sf_5")
        self.label_sf_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_sf_6.setGeometry(QtCore.QRect(150, 580, 111, 16))
        self.label_sf_6.setObjectName("label_sf_6")
        self.lineEdit_modifyFrame = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_modifyFrame.setGeometry(QtCore.QRect(150, 600, 151, 25))
        self.lineEdit_modifyFrame.setObjectName("lineEdit_modifyFrame")
        self.checkBox_translateX = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_translateX.setGeometry(QtCore.QRect(30, 460, 81, 16))
        self.checkBox_translateX.setChecked(False)
        self.checkBox_translateX.setObjectName("checkBox_translateX")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(15, 400, 411, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.checkBox_translateY = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_translateY.setGeometry(QtCore.QRect(110, 460, 81, 16))
        self.checkBox_translateY.setChecked(False)
        self.checkBox_translateY.setObjectName("checkBox_translateY")
        self.checkBox_translateZ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_translateZ.setGeometry(QtCore.QRect(190, 460, 81, 16))
        self.checkBox_translateZ.setObjectName("checkBox_translateZ")
        self.checkBox_rotateX = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_rotateX.setGeometry(QtCore.QRect(30, 490, 81, 16))
        self.checkBox_rotateX.setObjectName("checkBox_rotateX")
        self.checkBox_rotateY = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_rotateY.setGeometry(QtCore.QRect(110, 490, 81, 16))
        self.checkBox_rotateY.setObjectName("checkBox_rotateY")
        self.checkBox_rotateZ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_rotateZ.setGeometry(QtCore.QRect(190, 490, 81, 16))
        self.checkBox_rotateZ.setChecked(False)
        self.checkBox_rotateZ.setObjectName("checkBox_rotateZ")
        self.checkBox_scaleX = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_scaleX.setGeometry(QtCore.QRect(30, 520, 81, 16))
        self.checkBox_scaleX.setChecked(False)
        self.checkBox_scaleX.setObjectName("checkBox_scaleX")
        self.checkBox_scaleZ = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_scaleZ.setGeometry(QtCore.QRect(190, 520, 81, 16))
        self.checkBox_scaleZ.setObjectName("checkBox_scaleZ")
        self.checkBox_scaleY = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_scaleY.setGeometry(QtCore.QRect(110, 520, 81, 16))
        self.checkBox_scaleY.setChecked(False)
        self.checkBox_scaleY.setObjectName("checkBox_scaleY")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(15, 120, 420, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_sf_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_sf_7.setGeometry(QtCore.QRect(27, 136, 171, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_sf_7.setFont(font)
        self.label_sf_7.setObjectName("label_sf_7")
        self.horizontalSlider_numberJoints = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_numberJoints.setGeometry(QtCore.QRect(90, 80, 251, 25))
        self.horizontalSlider_numberJoints.setMinimum(1)
        self.horizontalSlider_numberJoints.setMaximum(300)
        self.horizontalSlider_numberJoints.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_numberJoints.setObjectName("horizontalSlider_numberJoints")
        self.checkBox_witImagePlanes = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_witImagePlanes.setGeometry(QtCore.QRect(130, 20, 111, 25))
        self.checkBox_witImagePlanes.setChecked(True)
        self.checkBox_witImagePlanes.setObjectName("checkBox_witImagePlanes")
        self.label_ef_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_ef_3.setGeometry(QtCore.QRect(250, 45, 61, 25))
        self.label_ef_3.setObjectName("label_ef_3")
        self.lineEdit_jointName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jointName.setGeometry(QtCore.QRect(312, 44, 111, 22))
        self.lineEdit_jointName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_jointName.setObjectName("lineEdit_jointName")
        self.pushButton_modifyName = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_modifyName.setGeometry(QtCore.QRect(40, 680, 181, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.pushButton_modifyName.setFont(font)
        self.pushButton_modifyName.setObjectName("pushButton_modifyName")
        self.label_sf_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_sf_8.setGeometry(QtCore.QRect(27, 313, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_sf_8.setFont(font)
        self.label_sf_8.setObjectName("label_sf_8")
        self.label_sf_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_sf_9.setGeometry(QtCore.QRect(27, 226, 231, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_sf_9.setFont(font)
        self.label_sf_9.setObjectName("label_sf_9")
        self.label_sf_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_sf_10.setGeometry(QtCore.QRect(20, 420, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_sf_10.setFont(font)
        self.label_sf_10.setObjectName("label_sf_10")
        self.checkBox_alphaGain = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_alphaGain.setGeometry(QtCore.QRect(250, 136, 73, 25))
        self.checkBox_alphaGain.setObjectName("checkBox_alphaGain")
        self.checkBox_colorGain = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_colorGain.setGeometry(QtCore.QRect(340, 136, 73, 25))
        self.checkBox_colorGain.setObjectName("checkBox_colorGain")
        self.checkBox_modify_alphaGain = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_modify_alphaGain.setGeometry(QtCore.QRect(30, 540, 73, 25))
        self.checkBox_modify_alphaGain.setObjectName("checkBox_modify_alphaGain")
        self.checkBox_modify_colorGain = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_modify_colorGain.setGeometry(QtCore.QRect(110, 540, 73, 25))
        self.checkBox_modify_colorGain.setObjectName("checkBox_modify_colorGain")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(15, 640, 411, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_sf_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_sf_11.setGeometry(QtCore.QRect(20, 650, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_sf_11.setFont(font)
        self.label_sf_11.setObjectName("label_sf_11")
        self.checkBox_modify_all = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_modify_all.setGeometry(QtCore.QRect(340, 460, 81, 16))
        self.checkBox_modify_all.setObjectName("checkBox_modify_all")
        self.radioButton_offsetV = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_offsetV.setGeometry(QtCore.QRect(170, 426, 91, 16))
        self.radioButton_offsetV.setChecked(True)
        self.radioButton_offsetV.setObjectName("radioButton_offsetV")
        self.radioButton_replaceV = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_replaceV.setGeometry(QtCore.QRect(280, 426, 111, 16))
        self.radioButton_replaceV.setObjectName("radioButton_replaceV")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.lineEdit_numberJoints.setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.label_sf.setText(QtWidgets.QApplication.translate("MainWindow", "create Joints", None, -1))
        self.label_ef.setText(QtWidgets.QApplication.translate("MainWindow", "amount", None, -1))
        self.pushButton_createJoint.setText(QtWidgets.QApplication.translate("MainWindow", "create Joint", None, -1))
        self.label_rt_2.setText(QtWidgets.QApplication.translate("MainWindow", "offset ", None, -1))
        self.pushButton_makeOffsetFrame.setText(QtWidgets.QApplication.translate("MainWindow", "offset Keys", None, -1))
        self.label_sf_2.setText(QtWidgets.QApplication.translate("MainWindow", "start frame", None, -1))
        self.label_ef_2.setText(QtWidgets.QApplication.translate("MainWindow", "end frame", None, -1))
        self.label_sf_3.setText(QtWidgets.QApplication.translate("MainWindow", "cutKey Frames", None, -1))
        self.pushButton_cutKeys.setText(QtWidgets.QApplication.translate("MainWindow", "cut Keys", None, -1))
        self.pushButton_alignKey.setText(QtWidgets.QApplication.translate("MainWindow", "align Keys", None, -1))
        self.label_sf_4.setText(QtWidgets.QApplication.translate("MainWindow", "align frame", None, -1))
        self.checkBox_offsetRandom.setText(QtWidgets.QApplication.translate("MainWindow", "random", None, -1))
        self.lineEdit_modifyValue.setText(QtWidgets.QApplication.translate("MainWindow", "1,1", None, -1))
        self.pushButton_makdModify.setText(QtWidgets.QApplication.translate("MainWindow", "modify Keys", None, -1))
        self.label_sf_5.setText(QtWidgets.QApplication.translate("MainWindow", "value (value,value)", None, -1))
        self.label_sf_6.setText(QtWidgets.QApplication.translate("MainWindow", "frames index [0,1,...]", None, -1))
        self.lineEdit_modifyFrame.setText(QtWidgets.QApplication.translate("MainWindow", "all", None, -1))
        self.checkBox_translateX.setText(QtWidgets.QApplication.translate("MainWindow", "translateX", None, -1))
        self.checkBox_translateY.setText(QtWidgets.QApplication.translate("MainWindow", "translateY", None, -1))
        self.checkBox_translateZ.setText(QtWidgets.QApplication.translate("MainWindow", "translateZ", None, -1))
        self.checkBox_rotateX.setText(QtWidgets.QApplication.translate("MainWindow", "rotateX", None, -1))
        self.checkBox_rotateY.setText(QtWidgets.QApplication.translate("MainWindow", "rotateY", None, -1))
        self.checkBox_rotateZ.setText(QtWidgets.QApplication.translate("MainWindow", "rotateZ", None, -1))
        self.checkBox_scaleX.setText(QtWidgets.QApplication.translate("MainWindow", "scaleX", None, -1))
        self.checkBox_scaleZ.setText(QtWidgets.QApplication.translate("MainWindow", "scaleZ", None, -1))
        self.checkBox_scaleY.setText(QtWidgets.QApplication.translate("MainWindow", "scaleY", None, -1))
        self.label_sf_7.setText(QtWidgets.QApplication.translate("MainWindow", "Cutting All Keys", None, -1))
        self.checkBox_witImagePlanes.setText(QtWidgets.QApplication.translate("MainWindow", "with image plane", None, -1))
        self.label_ef_3.setText(QtWidgets.QApplication.translate("MainWindow", "name proxy:", None, -1))
        self.lineEdit_jointName.setText(QtWidgets.QApplication.translate("MainWindow", "bone_", None, -1))
        self.pushButton_modifyName.setText(QtWidgets.QApplication.translate("MainWindow", "modify Joints and slot  Names", None, -1))
        self.label_sf_8.setText(QtWidgets.QApplication.translate("MainWindow", "Offset All Keys", None, -1))
        self.label_sf_9.setText(QtWidgets.QApplication.translate("MainWindow", "Align All Keys", None, -1))
        self.label_sf_10.setText(QtWidgets.QApplication.translate("MainWindow", "Random All Keys", None, -1))
        self.checkBox_alphaGain.setText(QtWidgets.QApplication.translate("MainWindow", "alpha Gain", None, -1))
        self.checkBox_colorGain.setText(QtWidgets.QApplication.translate("MainWindow", "color Gain", None, -1))
        self.checkBox_modify_alphaGain.setText(QtWidgets.QApplication.translate("MainWindow", "alpha Gain", None, -1))
        self.checkBox_modify_colorGain.setText(QtWidgets.QApplication.translate("MainWindow", "color Gain", None, -1))
        self.label_sf_11.setText(QtWidgets.QApplication.translate("MainWindow", "other tools", None, -1))
        self.checkBox_modify_all.setText(QtWidgets.QApplication.translate("MainWindow", "all", None, -1))
        self.radioButton_offsetV.setText(QtWidgets.QApplication.translate("MainWindow", "offset Value", None, -1))
        self.radioButton_replaceV.setText(QtWidgets.QApplication.translate("MainWindow", "replace Value", None, -1))




class mod_MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
   
    def __init__(self, parent= QtWidgets.QApplication.activeWindow()):
        super(mod_MainWindow, self).__init__(parent)
        #self.QTITEM.ACTION.connect(self.MODDEF)
        self.setupUi(self)
    #def self.MODDEF(self):



def main():
    global ui
    app = QtWidgets.QApplication.instance()
    if app == None: app = QtWidgets.QApplication(sys.argv)
    try:
        ui.close()
        ui.deleteLater()
    except: pass
    ui = mod_MainWindow()
    ui.show()
 
if __name__ == '__main__':
    main()


 