# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/alpha.DESKTOP-1S1STEK/Documents/GitHub/mayaTool/particleInstanceTool/particleinstancetool_01_UI_QT4.ui'
#
# Created: Wed Apr 19 10:55:05 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 505)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_sourceParticle = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_sourceParticle.setGeometry(QtCore.QRect(230, 40, 231, 31))
        self.lineEdit_sourceParticle.setObjectName("lineEdit_sourceParticle")
        self.pushButton_addObbject = QtGui.QPushButton(self.centralwidget)
        self.pushButton_addObbject.setGeometry(QtCore.QRect(30, 80, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_addObbject.setFont(font)
        self.pushButton_addObbject.setObjectName("pushButton_addObbject")
        self.listWidget_objList = QtGui.QListWidget(self.centralwidget)
        self.listWidget_objList.setGeometry(QtCore.QRect(230, 80, 231, 161))
        self.listWidget_objList.setObjectName("listWidget_objList")
        QtGui.QListWidgetItem(self.listWidget_objList)
        QtGui.QListWidgetItem(self.listWidget_objList)
        self.pushButton_getParticle = QtGui.QPushButton(self.centralwidget)
        self.pushButton_getParticle.setGeometry(QtCore.QRect(30, 40, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_getParticle.setFont(font)
        self.pushButton_getParticle.setObjectName("pushButton_getParticle")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 272, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.lineEdit_randomScale = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_randomScale.setGeometry(QtCore.QRect(150, 270, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lineEdit_randomScale.setFont(font)
        self.lineEdit_randomScale.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_randomScale.setObjectName("lineEdit_randomScale")
        self.lineEdit_randomPosition = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_randomPosition.setGeometry(QtCore.QRect(150, 290, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lineEdit_randomPosition.setFont(font)
        self.lineEdit_randomPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_randomPosition.setObjectName("lineEdit_randomPosition")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 292, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_Rotation = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Rotation.setGeometry(QtCore.QRect(150, 310, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lineEdit_Rotation.setFont(font)
        self.lineEdit_Rotation.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Rotation.setObjectName("lineEdit_Rotation")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 312, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 10, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_particleCount = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_particleCount.setGeometry(QtCore.QRect(390, 10, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lineEdit_particleCount.setFont(font)
        self.lineEdit_particleCount.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_particleCount.setReadOnly(True)
        self.lineEdit_particleCount.setObjectName("lineEdit_particleCount")
        self.comboBox_copyMode = QtGui.QComboBox(self.centralwidget)
        self.comboBox_copyMode.setGeometry(QtCore.QRect(100, 130, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.comboBox_copyMode.setFont(font)
        self.comboBox_copyMode.setObjectName("comboBox_copyMode")
        self.comboBox_copyMode.addItem("")
        self.comboBox_copyMode.addItem("")
        self.label_copyMode = QtGui.QLabel(self.centralwidget)
        self.label_copyMode.setGeometry(QtCore.QRect(-50, 138, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_copyMode.setFont(font)
        self.label_copyMode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_copyMode.setObjectName("label_copyMode")
        self.comboBox_displayMode = QtGui.QComboBox(self.centralwidget)
        self.comboBox_displayMode.setEnabled(False)
        self.comboBox_displayMode.setGeometry(QtCore.QRect(100, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.comboBox_displayMode.setFont(font)
        self.comboBox_displayMode.setObjectName("comboBox_displayMode")
        self.comboBox_displayMode.addItem("")
        self.comboBox_displayMode.addItem("")
        self.label_copyMode_2 = QtGui.QLabel(self.centralwidget)
        self.label_copyMode_2.setGeometry(QtCore.QRect(-50, 178, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_copyMode_2.setFont(font)
        self.label_copyMode_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_copyMode_2.setObjectName("label_copyMode_2")
        self.pushButton_create = QtGui.QPushButton(self.centralwidget)
        self.pushButton_create.setGeometry(QtCore.QRect(30, 420, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_create.setFont(font)
        self.pushButton_create.setObjectName("pushButton_create")
        self.label_copyMode_3 = QtGui.QLabel(self.centralwidget)
        self.label_copyMode_3.setGeometry(QtCore.QRect(-50, 218, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_copyMode_3.setFont(font)
        self.label_copyMode_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_copyMode_3.setObjectName("label_copyMode_3")
        self.comboBox_aimMode = QtGui.QComboBox(self.centralwidget)
        self.comboBox_aimMode.setEnabled(False)
        self.comboBox_aimMode.setGeometry(QtCore.QRect(100, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.comboBox_aimMode.setFont(font)
        self.comboBox_aimMode.setObjectName("comboBox_aimMode")
        self.comboBox_aimMode.addItem("")
        self.comboBox_aimMode.addItem("")
        self.lineEdit_errorMessage = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_errorMessage.setGeometry(QtCore.QRect(230, 270, 231, 121))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lineEdit_errorMessage.setFont(font)
        self.lineEdit_errorMessage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_errorMessage.setObjectName("lineEdit_errorMessage")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 250, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_spread = QtGui.QLabel(self.centralwidget)
        self.label_spread.setGeometry(QtCore.QRect(0, 342, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_spread.setFont(font)
        self.label_spread.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_spread.setObjectName("label_spread")
        self.lineEdit_spread = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_spread.setEnabled(False)
        self.lineEdit_spread.setGeometry(QtCore.QRect(150, 340, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lineEdit_spread.setFont(font)
        self.lineEdit_spread.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_spread.setObjectName("lineEdit_spread")
        self.label_multiple = QtGui.QLabel(self.centralwidget)
        self.label_multiple.setGeometry(QtCore.QRect(0, 372, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_multiple.setFont(font)
        self.label_multiple.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_multiple.setObjectName("label_multiple")
        self.lineEdit_multiple = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_multiple.setGeometry(QtCore.QRect(150, 370, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lineEdit_multiple.setFont(font)
        self.lineEdit_multiple.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_multiple.setObjectName("lineEdit_multiple")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_addObbject.setText(QtGui.QApplication.translate("MainWindow", "add Object into list", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget_objList.isSortingEnabled()
        self.listWidget_objList.setSortingEnabled(False)
        self.listWidget_objList.item(0).setText(QtGui.QApplication.translate("MainWindow", "aaa", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_objList.item(1).setText(QtGui.QApplication.translate("MainWindow", "bbb", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_objList.setSortingEnabled(__sortingEnabled)
        self.pushButton_getParticle.setText(QtGui.QApplication.translate("MainWindow", "get Source Particle", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "random Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_randomScale.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_randomPosition.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "random Position", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Rotation.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "random Rotation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "total particles Count", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_particleCount.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_copyMode.setItemText(0, QtGui.QApplication.translate("MainWindow", "duplicate", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_copyMode.setItemText(1, QtGui.QApplication.translate("MainWindow", "instance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_copyMode.setText(QtGui.QApplication.translate("MainWindow", "copy Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_displayMode.setItemText(0, QtGui.QApplication.translate("MainWindow", "Bounding Box", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_displayMode.setItemText(1, QtGui.QApplication.translate("MainWindow", "shaded", None, QtGui.QApplication.UnicodeUTF8))
        self.label_copyMode_2.setText(QtGui.QApplication.translate("MainWindow", "display Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_create.setText(QtGui.QApplication.translate("MainWindow", "create", None, QtGui.QApplication.UnicodeUTF8))
        self.label_copyMode_3.setText(QtGui.QApplication.translate("MainWindow", "aim Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_aimMode.setItemText(0, QtGui.QApplication.translate("MainWindow", "always top", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_aimMode.setItemText(1, QtGui.QApplication.translate("MainWindow", "normal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "error message", None, QtGui.QApplication.UnicodeUTF8))
        self.label_spread.setText(QtGui.QApplication.translate("MainWindow", "spread", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_spread.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_multiple.setText(QtGui.QApplication.translate("MainWindow", "multiple", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_multiple.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))

