# -*- coding: utf-8 -*-

from PySide2 import QtCore, QtGui, QtWidgets

class buildUI():


    def __init__(self, centralwidget):
        print 'inital buildUI'
        self.centralwidget = centralwidget
        #print self.centralwidget

        #print buttonText
        #print buttonPosition
        #self.buttonAdd = QtWidgets.QPushButton(parent)


    def createTable(self,parent,tableName,size,rowCount,rowSize,columnCount,columnSize,
                    tableBGColor,
                    itemBGColor,
                    itemSelectColor,
                    itemHoverColor):
        '''
            tableName: string
            size: [int,int,int,int] table size
            rowCount : int
            rowSize: int
            columnCount: int
            columnSize:[int,int,.....]
            tableBGColor : [int,int,int]  0~255
            itemBGColor : [int,int,int]  0~255
            itemSelectColor : [int,int,int]  0~255
            itemHoverColor : [int,int,int]  0~255
        '''



        tableWidget = QtWidgets.QTableWidget(parent)
        #return tableWidget
        tableWidget.setGeometry(QtCore.QRect(size[0],size[1],size[2],size[3]))
        tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        tableWidget.setLineWidth(1)
        tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        tableWidget.setDragEnabled(True)
        tableWidget.setAlternatingRowColors(False)
        tableWidget.setGridStyle(QtCore.Qt.SolidLine) #grid line
        tableWidget.setRowCount(rowCount)
        tableWidget.setColumnCount(columnCount)
        for i in range(0,columnCount):
            tableWidget.setColumnWidth(i,columnSize[i])

        #tableBGColor = [100,200,200]
        #itemBGColor = [255,255,0]
        #itemSelectColor = [255,0,0]
        #itemHoverColor = [0,200,0]
        tableWidget.setObjectName(tableName)

        tableWidget.verticalHeader().setDefaultSectionSize(rowSize)

        tableWidget.horizontalHeader().setVisible(False)

        tableWidget.verticalHeader().setVisible(False)
        tableWidget.setStyleSheet("\
                    QTableWidget {\
                        background-color: rgb(%s,%s,%s);\
                    }\
                    QTableWidget::item {\
                        background-color: rgb(%s,%s,%s);\
                    }\
                    QTableWidget::item:selected {\
                        background-color: rgb(%s,%s,%s);\
                    }\
                    QTableWidget::item:hover {\
                        background-color: rgb(%s,%s,%s);\
                    }\
                    "%(tableBGColor[0],tableBGColor[1],tableBGColor[2],
                    itemBGColor[0],itemBGColor[1],itemBGColor[2],
                    itemSelectColor[0],itemSelectColor[1],itemSelectColor[2],
                    itemHoverColor[0],itemHoverColor[1],itemHoverColor[2])
                    )

        return tableWidget
            #"QTableWidget::item {background-color: rgb(200,200,200);"
            #"QTableWidget::item:selected {background-color: blue;}"
            #"QTableWidget::item:hover {background-color: red;}"
            #tableBGColor[0],tableBGColor[1],tableBGColor[2]


    def projectButtonA(self,parent,buttonName,position,iconPathA,iconPathB,iconSize,checkAble):
        '''
        buttonName:string
        position:[int,int,int,int]
        iconPath:string, fileName path
        iconSize:[int,int]
        '''
        projectButtonA = QtWidgets.QPushButton(parent)
        projectButtonA.setGeometry(QtCore.QRect(position[0],position[1],position[2],position[3]))
        projectButtonA.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(iconPathA), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(iconPathA), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(iconPathB), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(iconPathB), QtGui.QIcon.Selected, QtGui.QIcon.On)

        projectButtonA.setIcon(icon)
        projectButtonA.setIconSize(QtCore.QSize(iconSize[0],iconSize[1]))
        projectButtonA.setFlat(True)
        projectButtonA.setCheckable(checkAble)

        projectButtonA.setObjectName(buttonName)
        return projectButtonA




    def projectButtonB(self,parent,buttonName,buttonText,setEnabledState,checkAble,flatState,
                        buttonBGColor,
                        buttonCheckBGColor,
                        buttonHoverColor):

        '''
        parent: parent item
        buttonText: string
        checkAble :boolean
        setEnabledState:boolean
        flatState:boolean
        buttonBGColor : [int,int,int]  0~255
        buttonTextColor : [int,int,int]  0~255
        buttonCheckBGColor : [int,int,int]  0~255
        buttonCheckTextColor : [int,int,int]  0~255
        buttonHoverColor : [int,int,int]  0~255

        '''
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)

        projectButtonB = QtWidgets.QPushButton(parent)
        projectButtonB.setText(buttonText)
        projectButtonB.setCheckable(checkAble)
        projectButtonB.setObjectName(buttonName)
        projectButtonB.setFlat(flatState)
        projectButtonB.setEnabled(setEnabledState)
        projectButtonB.setFont(font)
        projectButtonB.setAutoFillBackground(False)
        projectButtonB.setStyleSheet("\
                QPushButton {\
                    background-color:rgb(70,70,70);\
                    color:blue;\
                }\
                QPushButton:pressed {\
                    background-color:yellow;\
                    color:white;\
                }\
                ")


        return projectButtonB


    def projectButtonB2(self,parent,buttonName,buttonText,setEnabledState,checkAble,flatState,
                        buttonBGColor,
                        buttonCheckBGColor,
                        buttonHoverColor):

        '''
        parent: parent item
        buttonText: string
        checkAble :boolean
        setEnabledState:boolean
        flatState:boolean
        buttonBGColor : [int,int,int]  0~255
        buttonTextColor : [int,int,int]  0~255
        buttonCheckBGColor : [int,int,int]  0~255
        buttonCheckTextColor : [int,int,int]  0~255
        buttonHoverColor : [int,int,int]  0~255

        '''
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)

        projectButtonB = QtWidgets.QPushButton(parent)
        projectButtonB.setText(buttonText)
        projectButtonB.setCheckable(checkAble)
        projectButtonB.setObjectName(buttonName)
        projectButtonB.setFlat(flatState)
        projectButtonB.setEnabled(setEnabledState)
        projectButtonB.setFont(font)
        projectButtonB.setAutoFillBackground(False)
        projectButtonB.setStyleSheet("\
                QPushButton {   \
                    background-color: rgb(%s,%s,%s);\
                    color:blue;\
                }   \
                QPushButton::checked {\
                    background-color: yellow;\
                    color:red;\
                }\
                QPushButton::hover {  \
                    background-color: rgb(%s, %s, %s); \
                }  \
                "%(buttonBGColor[0],buttonBGColor[1],buttonBGColor[2],
                #buttonCheckBGColor[0],buttonCheckBGColor[1],buttonCheckBGColor[2],
                buttonHoverColor[0],buttonHoverColor[1],buttonHoverColor[2])
                )


        return projectButtonB


    def addAssetCard(self,nameCardPosition):

        self.AssetSQ_FrameSmall = QtWidgets.QFrame(self.centralwidget)
        self.AssetSQ_FrameSmall.setGeometry(QtCore.QRect(nameCardPosition[0],
                                            nameCardPosition[1],
                                            nameCardPosition[2],
                                            nameCardPosition[3]))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_concept_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_concept_02.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_concept_01.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_concept_02.png"), QtGui.QIcon.Active, QtGui.QIcon.On)

        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_mod_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_mod_02.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_mod_01.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Tex_02.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Tex_01.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Tex_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Tex_01.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Tex_02.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Tex_02.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Rig_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Rig_02.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/button_Asset_Rig_02.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block_Check.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block_Check.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block_Check.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block_B.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block_C.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/userBlockE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/user_block_D.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.AssetSQ_FrameSmall.setMaximumSize(QtCore.QSize(550, 30))
        self.AssetSQ_FrameSmall.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AssetSQ_FrameSmall.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AssetSQ_FrameSmall.setObjectName("AssetSQ_FrameSmall")
        self.ASLS_labelA = QtWidgets.QLabel(self.AssetSQ_FrameSmall)
        self.ASLS_labelA.setGeometry(QtCore.QRect(27, 2, 225, 25))
        self.ASLS_labelA.setMinimumSize(QtCore.QSize(200, 25))
        self.ASLS_labelA.setMaximumSize(QtCore.QSize(400, 25))
        self.ASLS_labelA.setText("")
        self.ASLS_labelA.setPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/assetLong_A01.png"))
        self.ASLS_labelA.setScaledContents(True)
        self.ASLS_labelA.setObjectName("ASLS_labelA")
        self.ASLS_buttonM = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonM.setEnabled(True)
        self.ASLS_buttonM.setGeometry(QtCore.QRect(276, 4, 22, 22))
        self.ASLS_buttonM.setMaximumSize(QtCore.QSize(22, 22))
        self.ASLS_buttonM.setAutoFillBackground(False)
        self.ASLS_buttonM.setText("")
        self.ASLS_buttonM.setIcon(icon1)
        self.ASLS_buttonM.setIconSize(QtCore.QSize(22, 22))
        self.ASLS_buttonM.setCheckable(True)
        self.ASLS_buttonM.setFlat(True)
        self.ASLS_buttonM.setObjectName("ASLS_buttonM")
        self.ASLS_buttonC = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonC.setGeometry(QtCore.QRect(252, 4, 22, 22))
        self.ASLS_buttonC.setMaximumSize(QtCore.QSize(22, 22))
        self.ASLS_buttonC.setAutoFillBackground(False)
        self.ASLS_buttonC.setText("")
        self.ASLS_buttonC.setIcon(icon)
        self.ASLS_buttonC.setIconSize(QtCore.QSize(22, 22))
        self.ASLS_buttonC.setCheckable(True)
        self.ASLS_buttonC.setFlat(True)
        self.ASLS_buttonC.setObjectName("ASLS_buttonC")
        self.ASLS_buttonT = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonT.setEnabled(True)
        self.ASLS_buttonT.setGeometry(QtCore.QRect(300, 4, 22, 22))
        self.ASLS_buttonT.setMaximumSize(QtCore.QSize(22, 22))
        self.ASLS_buttonT.setAutoFillBackground(False)
        self.ASLS_buttonT.setText("")
        self.ASLS_buttonT.setIcon(icon2)
        self.ASLS_buttonT.setIconSize(QtCore.QSize(22, 22))
        self.ASLS_buttonT.setCheckable(True)
        self.ASLS_buttonT.setFlat(True)
        self.ASLS_buttonT.setObjectName("ASLS_buttonT")
        self.ASLS_buttonR = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonR.setGeometry(QtCore.QRect(324, 4, 22, 22))
        self.ASLS_buttonR.setMaximumSize(QtCore.QSize(22, 22))
        self.ASLS_buttonR.setAutoFillBackground(False)
        self.ASLS_buttonR.setText("")
        self.ASLS_buttonR.setIcon(icon3)
        self.ASLS_buttonR.setIconSize(QtCore.QSize(22, 22))
        self.ASLS_buttonR.setCheckable(True)
        self.ASLS_buttonR.setFlat(True)
        self.ASLS_buttonR.setObjectName("ASLS_buttonR")
        self.ASLS_labelB = QtWidgets.QLabel(self.AssetSQ_FrameSmall)
        self.ASLS_labelB.setGeometry(QtCore.QRect(346, 2, 100, 25))
        self.ASLS_labelB.setMinimumSize(QtCore.QSize(100, 15))
        self.ASLS_labelB.setMaximumSize(QtCore.QSize(200, 25))
        self.ASLS_labelB.setText("")
        self.ASLS_labelB.setPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/userBlockB.png"))
        self.ASLS_labelB.setScaledContents(True)
        self.ASLS_labelB.setObjectName("ASLS_labelB")
        self.ASLS_textA = QtWidgets.QLabel(self.AssetSQ_FrameSmall)
        self.ASLS_textA.setGeometry(QtCore.QRect(38, 8, 200, 14))
        self.ASLS_textA.setMaximumSize(QtCore.QSize(200, 14))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(76, 85, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 85, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.ASLS_textA.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.ASLS_textA.setFont(font)
        self.ASLS_textA.setObjectName("ASLS_textA")
        self.ASLS_textB = QtWidgets.QLabel(self.AssetSQ_FrameSmall)
        self.ASLS_textB.setGeometry(QtCore.QRect(360, 8, 81, 14))
        self.ASLS_textB.setMaximumSize(QtCore.QSize(100, 14))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(76, 85, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 85, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ASLS_textB.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.ASLS_textB.setFont(font)
        self.ASLS_textB.setObjectName("ASLS_textB")
        self.ASLS_buttonA = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_buttonA.setGeometry(QtCore.QRect(2, 2, 25, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.ASLS_buttonA.setPalette(palette)
        self.ASLS_buttonA.setAutoFillBackground(False)
        self.ASLS_buttonA.setText("")
        self.ASLS_buttonA.setIcon(icon6)
        self.ASLS_buttonA.setIconSize(QtCore.QSize(25, 25))
        self.ASLS_buttonA.setCheckable(True)
        self.ASLS_buttonA.setFlat(True)
        self.ASLS_buttonA.setObjectName("ASLS_buttonA")
        self.ASLS_button_stateA = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_button_stateA.setEnabled(False)
        self.ASLS_button_stateA.setGeometry(QtCore.QRect(445, 3, 23, 23))
        self.ASLS_button_stateA.setText("")
        self.ASLS_button_stateA.setIcon(icon7)
        self.ASLS_button_stateA.setIconSize(QtCore.QSize(23, 28))
        self.ASLS_button_stateA.setCheckable(True)
        self.ASLS_button_stateA.setFlat(True)
        self.ASLS_button_stateA.setObjectName("ASLS_button_stateA")
        self.ASLS_button_stateB = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_button_stateB.setEnabled(False)
        self.ASLS_button_stateB.setGeometry(QtCore.QRect(467, 3, 23, 23))
        self.ASLS_button_stateB.setText("")
        self.ASLS_button_stateB.setIcon(icon8)
        self.ASLS_button_stateB.setIconSize(QtCore.QSize(23, 28))
        self.ASLS_button_stateB.setCheckable(True)
        self.ASLS_button_stateB.setFlat(True)
        self.ASLS_button_stateB.setObjectName("ASLS_button_stateB")
        self.ASLS_button_stateC = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_button_stateC.setEnabled(False)
        self.ASLS_button_stateC.setGeometry(QtCore.QRect(489, 3, 23, 23))
        self.ASLS_button_stateC.setText("")
        self.ASLS_button_stateC.setIcon(icon9)
        self.ASLS_button_stateC.setIconSize(QtCore.QSize(23, 28))
        self.ASLS_button_stateC.setCheckable(True)
        self.ASLS_button_stateC.setFlat(True)
        self.ASLS_button_stateC.setObjectName("ASLS_button_stateC")
        self.ASLS_button_stateD = QtWidgets.QPushButton(self.AssetSQ_FrameSmall)
        self.ASLS_button_stateD.setEnabled(False)
        self.ASLS_button_stateD.setGeometry(QtCore.QRect(511, 3, 23, 23))
        self.ASLS_button_stateD.setText("")
        self.ASLS_button_stateD.setIcon(icon10)
        self.ASLS_button_stateD.setIconSize(QtCore.QSize(23, 28))
        self.ASLS_button_stateD.setCheckable(True)
        self.ASLS_button_stateD.setFlat(True)
        self.ASLS_button_stateD.setObjectName("ASLS_button_stateD")

        self.ASLS_textA.setText(QtWidgets.QApplication.translate("MainWindow", "AssetName", None, -1))
        self.ASLS_textB.setText(QtWidgets.QApplication.translate("MainWindow", "User", None, -1))



    def addNameCard(self,nameCardPosition,name,dept,sec,specA,specB):
        self.NameCard_frame = QtWidgets.QFrame(self.centralwidget)
        self.NameCard_frame.setGeometry(QtCore.QRect(nameCardPosition[0],
                                            nameCardPosition[1],
                                            nameCardPosition[2],
                                            nameCardPosition[3]))
        #self.NameCard_frame.setGeometry(QtCore.QRect(200, 120, 300, 100))
        #self.NameCard_frame = QtWidgets.QFrame(self.centralwidget)
        #self.NameCard_frame.setGeometry(QtCore.QRect(200, 120, 300, 100))
        self.NameCard_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NameCard_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NameCard_frame.setObjectName("NameCard_frame")
        self.NC_BGImageLabelA = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_BGImageLabelA.setGeometry(QtCore.QRect(0, 0, 300, 100))
        self.NC_BGImageLabelA.setText("")
        self.NC_BGImageLabelA.setPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/colorTemplate_A001.png"))
        self.NC_BGImageLabelA.setScaledContents(True)
        self.NC_BGImageLabelA.setObjectName("NC_BGImageLabelA")
        self.NC_buttonA = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonA.setGeometry(QtCore.QRect(0, 0, 12, 25))
        self.NC_buttonA.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/colorTemplate_C001.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NC_buttonA.setIcon(icon)
        self.NC_buttonA.setIconSize(QtCore.QSize(25, 25))
        self.NC_buttonA.setFlat(False)
        self.NC_buttonA.setObjectName("NC_buttonA")
        self.NC_buttonB = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonB.setGeometry(QtCore.QRect(0, 25, 12, 25))
        self.NC_buttonB.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/colorTemplate_C002.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NC_buttonB.setIcon(icon1)
        self.NC_buttonB.setIconSize(QtCore.QSize(25, 25))
        self.NC_buttonB.setFlat(False)
        self.NC_buttonB.setObjectName("NC_buttonB")
        self.NC_buttonC = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonC.setGeometry(QtCore.QRect(0, 50, 12, 25))
        self.NC_buttonC.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/colorTemplate_C003.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NC_buttonC.setIcon(icon2)
        self.NC_buttonC.setIconSize(QtCore.QSize(25, 25))
        self.NC_buttonC.setFlat(False)
        self.NC_buttonC.setObjectName("NC_buttonC")
        self.NC_buttonD = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonD.setGeometry(QtCore.QRect(0, 75, 12, 25))
        self.NC_buttonD.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/colorTemplate_C004.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NC_buttonD.setIcon(icon3)
        self.NC_buttonD.setIconSize(QtCore.QSize(25, 25))
        self.NC_buttonD.setFlat(False)
        self.NC_buttonD.setObjectName("NC_buttonD")
        self.NC_BGImageLabelB = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_BGImageLabelB.setGeometry(QtCore.QRect(12, 1, 96, 96))
        self.NC_BGImageLabelB.setText("")
        self.NC_BGImageLabelB.setPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/colorTemplate_A002.png"))
        self.NC_BGImageLabelB.setScaledContents(True)
        self.NC_BGImageLabelB.setObjectName("NC_BGImageLabelB")
        self.NC_InfoTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_InfoTextLabel.setGeometry(QtCore.QRect(120, 1, 61, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_InfoTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_InfoTextLabel.setFont(font)
        self.NC_InfoTextLabel.setObjectName("NC_InfoTextLabel")
        self.NC_NameTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_NameTextLabel.setGeometry(QtCore.QRect(120, 20, 61, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_NameTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_NameTextLabel.setFont(font)
        self.NC_NameTextLabel.setObjectName("NC_NameTextLabel")
        self.NC_DeptTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_DeptTextLabel.setGeometry(QtCore.QRect(125, 40, 27, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_DeptTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_DeptTextLabel.setFont(font)
        self.NC_DeptTextLabel.setObjectName("NC_DeptTextLabel")
        self.NC_SecTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_SecTextLabel.setGeometry(QtCore.QRect(200, 40, 25, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_SecTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_SecTextLabel.setFont(font)
        self.NC_SecTextLabel.setObjectName("NC_SecTextLabel")
        self.NC_specATextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_specATextLabel.setGeometry(QtCore.QRect(125, 60, 150, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_specATextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_specATextLabel.setFont(font)
        self.NC_specATextLabel.setObjectName("NC_specATextLabel")
        self.NC_specBTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_specBTextLabel.setGeometry(QtCore.QRect(125, 80, 150, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_specBTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_specBTextLabel.setFont(font)
        self.NC_specBTextLabel.setObjectName("NC_specBTextLabel")
        self.NC_DeptValueTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_DeptValueTextLabel.setGeometry(QtCore.QRect(158, 40, 40, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_DeptValueTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_DeptValueTextLabel.setFont(font)
        self.NC_DeptValueTextLabel.setObjectName("NC_DeptValueTextLabel")
        self.NC_SecValueTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_SecValueTextLabel.setGeometry(QtCore.QRect(225, 40, 50, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_SecValueTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_SecValueTextLabel.setFont(font)
        self.NC_SecValueTextLabel.setObjectName("NC_SecValueTextLabel")
        self.NC_buttonE = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonE.setGeometry(QtCore.QRect(13, 1, 100, 98))
        self.NC_buttonE.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/noImage_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NC_buttonE.setIcon(icon4)
        self.NC_buttonE.setIconSize(QtCore.QSize(100, 100))
        self.NC_buttonE.setFlat(True)
        self.NC_buttonE.setObjectName("NC_buttonE")
        self.NC_buttonG = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonG.setGeometry(QtCore.QRect(284, 1, 15, 15))
        self.NC_buttonG.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/sub_002.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NC_buttonG.setIcon(icon5)
        self.NC_buttonG.setIconSize(QtCore.QSize(15, 15))
        self.NC_buttonG.setFlat(True)
        self.NC_buttonG.setObjectName("NC_buttonG")
        self.NC_InfoTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", "INFO :", None, -1))
        self.NC_NameTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", name , None, -1))
        self.NC_DeptTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", "DEPT.", None, -1))
        self.NC_SecTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", "SEC.", None, -1))
        self.NC_specATextLabel.setText(QtWidgets.QApplication.translate("MainWindow", specA, None, -1))
        self.NC_specBTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", specB, None, -1))
        self.NC_DeptValueTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", dept, None, -1))
        self.NC_SecValueTextLabel.setText(QtWidgets.QApplication.translate("MainWindow",sec, None, -1))


    def addSmallNameCard(self,nameCardPosition,name,dept,sec,specA,
                            baseColor,buttonAColor,buttonBColor,
                            labelAColor,labelBColor,labelCColor,labelDColor,labelEColor,progressBarValue):
        self.NameCard_frame = QtWidgets.QFrame(self.centralwidget)
        self.NameCard_frame.setGeometry(QtCore.QRect(nameCardPosition[0],
                                            nameCardPosition[1],
                                            nameCardPosition[2],
                                            nameCardPosition[3]))
        #self.NameCard_frame.setGeometry(QtCore.QRect(200, 120, 300, 50))

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(baseColor[0],baseColor[1],baseColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(baseColor[0],baseColor[1],baseColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(baseColor[0],baseColor[1],baseColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(baseColor[0],baseColor[1],baseColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.NameCard_frame.setPalette(palette)
        self.NameCard_frame.setAutoFillBackground(True)
        self.NameCard_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NameCard_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NameCard_frame.setObjectName("NameCard_frame")
        self.NC_BGImageLabelB = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_BGImageLabelB.setGeometry(QtCore.QRect(13, 1, 48, 48))
        self.NC_BGImageLabelB.setText("")
        self.NC_BGImageLabelB.setPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/colorTemplate_A002.png"))
        self.NC_BGImageLabelB.setScaledContents(True)
        self.NC_BGImageLabelB.setObjectName("NC_BGImageLabelB")
        self.NC_NameTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_NameTextLabel.setGeometry(QtCore.QRect(67, 5, 61, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_NameTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_NameTextLabel.setFont(font)
        self.NC_NameTextLabel.setObjectName("NC_NameTextLabel")
        self.NC_DeptTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_DeptTextLabel.setGeometry(QtCore.QRect(67, 19, 27, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_DeptTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_DeptTextLabel.setFont(font)
        self.NC_DeptTextLabel.setObjectName("NC_DeptTextLabel")
        self.NC_SecTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_SecTextLabel.setGeometry(QtCore.QRect(140, 19, 25, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_SecTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_SecTextLabel.setFont(font)
        self.NC_SecTextLabel.setObjectName("NC_SecTextLabel")
        self.NC_DeptValueTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_DeptValueTextLabel.setGeometry(QtCore.QRect(100, 19, 40, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_DeptValueTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_DeptValueTextLabel.setFont(font)
        self.NC_DeptValueTextLabel.setObjectName("NC_DeptValueTextLabel")
        self.NC_SecValueTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_SecValueTextLabel.setGeometry(QtCore.QRect(168, 19, 50, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_SecValueTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_SecValueTextLabel.setFont(font)
        self.NC_SecValueTextLabel.setObjectName("NC_SecValueTextLabel")
        self.NC_buttonG = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonG.setGeometry(QtCore.QRect(253, 2, 15, 15))
        self.NC_buttonG.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/sub_002.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NC_buttonG.setIcon(icon)
        self.NC_buttonG.setIconSize(QtCore.QSize(15, 15))
        self.NC_buttonG.setFlat(True)
        self.NC_buttonG.setObjectName("NC_buttonG")
        self.NC_buttonE = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonE.setGeometry(QtCore.QRect(14, 3, 50, 50))
        self.NC_buttonE.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/noImage_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NC_buttonE.setIcon(icon1)
        self.NC_buttonE.setIconSize(QtCore.QSize(50, 60))
        self.NC_buttonE.setFlat(True)
        self.NC_buttonE.setObjectName("NC_buttonE")
        self.NC_specTextLabel = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_specTextLabel.setGeometry(QtCore.QRect(67, 33, 40, 15))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.NC_specTextLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_specTextLabel.setFont(font)
        self.NC_specTextLabel.setObjectName("NC_specTextLabel")
        self.NC_progressBar = QtWidgets.QProgressBar(self.NameCard_frame)
        self.NC_progressBar.setGeometry(QtCore.QRect(67, 48, 200, 3))
        self.NC_progressBar.setMaximumSize(QtCore.QSize(204, 3))
        self.NC_progressBar.setProperty("value", progressBarValue)
        self.NC_progressBar.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.NC_progressBar.setTextVisible(False)
        self.NC_progressBar.setObjectName("NC_progressBar")
        self.NC_stateLabelA = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_stateLabelA.setGeometry(QtCore.QRect(95, 2, 30, 5))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelAColor[0],labelAColor[1],labelAColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelAColor[0],labelAColor[1],labelAColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelAColor[0],labelAColor[1],labelAColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelAColor[0],labelAColor[1],labelAColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.NC_stateLabelA.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_stateLabelA.setFont(font)
        self.NC_stateLabelA.setAutoFillBackground(True)
        self.NC_stateLabelA.setText("")
        self.NC_stateLabelA.setObjectName("NC_stateLabelA")
        self.NC_stateLabelB = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_stateLabelB.setGeometry(QtCore.QRect(125, 2, 30, 5))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelBColor[0],labelBColor[1],labelBColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelBColor[0],labelBColor[1],labelBColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelBColor[0],labelBColor[1],labelBColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelBColor[0],labelBColor[1],labelBColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.NC_stateLabelB.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_stateLabelB.setFont(font)
        self.NC_stateLabelB.setAutoFillBackground(True)
        self.NC_stateLabelB.setText("")
        self.NC_stateLabelB.setObjectName("NC_stateLabelB")
        self.NC_stateLabelC = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_stateLabelC.setGeometry(QtCore.QRect(155, 2, 30, 5))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelCColor[0],labelCColor[1],labelCColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelCColor[0],labelCColor[1],labelCColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelCColor[0],labelCColor[1],labelCColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelCColor[0],labelCColor[1],labelCColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.NC_stateLabelC.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_stateLabelC.setFont(font)
        self.NC_stateLabelC.setAutoFillBackground(True)
        self.NC_stateLabelC.setText("")
        self.NC_stateLabelC.setObjectName("NC_stateLabelC")
        self.NC_stateLabelD = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_stateLabelD.setGeometry(QtCore.QRect(185, 2, 30, 5))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelDColor[0],labelDColor[1],labelDColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelDColor[0],labelDColor[1],labelDColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelDColor[0],labelDColor[1],labelDColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelDColor[0],labelDColor[1],labelDColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.NC_stateLabelD.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_stateLabelD.setFont(font)
        self.NC_stateLabelD.setAutoFillBackground(True)
        self.NC_stateLabelD.setText("")
        self.NC_stateLabelD.setObjectName("NC_stateLabelD")
        self.NC_stateLabelE = QtWidgets.QLabel(self.NameCard_frame)
        self.NC_stateLabelE.setGeometry(QtCore.QRect(215, 2, 30, 5))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelEColor[0],labelEColor[1],labelEColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelEColor[0],labelEColor[1],labelEColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelEColor[0],labelEColor[1],labelEColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(labelEColor[0],labelEColor[1],labelEColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.NC_stateLabelE.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.NC_stateLabelE.setFont(font)
        self.NC_stateLabelE.setAutoFillBackground(True)
        self.NC_stateLabelE.setText("")
        self.NC_stateLabelE.setObjectName("NC_stateLabelE")
        self.NC_buttonA = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonA.setGeometry(QtCore.QRect(2, 3, 10, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(buttonAColor[0], buttonAColor[0], buttonAColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(buttonAColor[0], buttonAColor[0], buttonAColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(buttonAColor[0], buttonAColor[0], buttonAColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.NC_buttonA.setPalette(palette)
        self.NC_buttonA.setAutoFillBackground(True)
        self.NC_buttonA.setText("")
        self.NC_buttonA.setFlat(True)
        self.NC_buttonA.setObjectName("NC_buttonA")
        self.NC_buttonB = QtWidgets.QPushButton(self.NameCard_frame)
        self.NC_buttonB.setGeometry(QtCore.QRect(2, 29, 10, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(buttonBColor[0], buttonBColor[0], buttonBColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(buttonBColor[0], buttonBColor[0], buttonBColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(buttonBColor[0], buttonBColor[0], buttonBColor[2]))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.NC_buttonB.setPalette(palette)
        self.NC_buttonB.setAutoFillBackground(True)
        self.NC_buttonB.setText("")
        self.NC_buttonB.setFlat(True)
        self.NC_buttonB.setObjectName("NC_buttonB")


        self.NC_NameTextLabel.setText(QtWidgets.QApplication.translate("MainWindow",name, None, -1))
        self.NC_DeptTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", "DEPT.", None, -1))
        self.NC_SecTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", "SEC.", None, -1))
        self.NC_DeptValueTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", dept, None, -1))
        self.NC_SecValueTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", sec, None, -1))
        self.NC_specTextLabel.setText(QtWidgets.QApplication.translate("MainWindow", specA, None, -1))

    def addProjectCard(self,parent,projectName,num):
        addProject_Frame = QtWidgets.QFrame(parent,num)
        addProject_Frame.setGeometry(QtCore.QRect(2, num, 191, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        addProject_Frame.setPalette(palette)
        addProject_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        addProject_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        addProject_Frame.setObjectName("addProject_Frame")
        addProject_buttonLabel = QtWidgets.QPushButton(addProject_Frame)
        addProject_buttonLabel.setGeometry(QtCore.QRect(30, 0, 150, 30))
        addProject_buttonLabel.setMinimumSize(QtCore.QSize(150, 30))
        addProject_buttonLabel.setMaximumSize(QtCore.QSize(150, 30))
        addProject_buttonLabel.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/label_G1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addProject_buttonLabel.setIcon(icon)
        addProject_buttonLabel.setIconSize(QtCore.QSize(150, 30))
        addProject_buttonLabel.setFlat(True)
        addProject_buttonLabel.setObjectName("addProject_buttonLabel")
        addProject_labelName = QtWidgets.QLabel(addProject_Frame)
        addProject_labelName.setGeometry(QtCore.QRect(41, 7, 120, 16))
        addProject_labelName.setMinimumSize(QtCore.QSize(120, 16))
        addProject_labelName.setMaximumSize(QtCore.QSize(120, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        addProject_labelName.setFont(font)
        addProject_labelName.setObjectName("addProject_labelName")
        addProject_buttonCheck = QtWidgets.QPushButton(addProject_Frame)
        addProject_buttonCheck.setGeometry(QtCore.QRect(0, 0, 30, 30))
        addProject_buttonCheck.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/alphaOnly/github/pipelineTool/UI/label_G2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addProject_buttonCheck.setIcon(icon1)
        addProject_buttonCheck.setIconSize(QtCore.QSize(30, 30))
        addProject_buttonCheck.setFlat(True)
        addProject_buttonCheck.setObjectName("addProject_buttonCheck")


        addProject_labelName.setText(QtWidgets.QApplication.translate("MainWindow", projectName, None, -1))






    def addButton(self,buttonText,buttonPosition):
        print buttonText
        print buttonPosition
        buttonAdd = QtWidgets.QPushButton(self.centralwidget)

        buttonAdd.setGeometry(QtCore.QRect(buttonPosition[0],
                                            buttonPosition[1],
                                            buttonPosition[2],
                                            buttonPosition[3]))
        buttonAdd.setText(QtWidgets.QApplication.translate("Form", buttonText, None, -1))

        #buttonAdd.setObjectName('sdsd')

    def addLabel(self,buttonPosition):
        label = QtWidgets.QLabel(self.centralwidget)
        label.setMinimumSize(QtCore.QSize(60, 60))
        label.setMaximumSize(QtCore.QSize(60, 60))
        label.setGeometry(QtCore.QRect(buttonPosition[0],
                                            buttonPosition[1],
                                            buttonPosition[2],
                                            buttonPosition[3]))
        #label.setAutoFillBackground(False)
        label.setFrameShape(QtWidgets.QFrame.Box)
        label.setFrameShadow(QtWidgets.QFrame.Sunken)
        label.setText("no image")
        #label.setPixmap(QtGui.QPixmap("../prefs/icons/UI/cat-alt-256.png"))
        label.setScaledContents(True)
        #label.setObjectName("label_3")
