# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/alpha/Documents/maya/2017/scripts/userTemplateA.ui'
#
# Created: Wed Dec 13 18:04:00 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(520, 70, 271, 92))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.jobCardLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.jobCardLayout.setSpacing(1)
        self.jobCardLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.jobCardLayout.setContentsMargins(3, 1, 3, 1)
        self.jobCardLayout.setObjectName("jobCardLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setContentsMargins(1, 3, 1, 3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.progressBar_5 = QtWidgets.QProgressBar(self.horizontalLayoutWidget_6)
        self.progressBar_5.setMaximumSize(QtCore.QSize(60, 10))
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.progressBar_5.setObjectName("progressBar_5")
        self.verticalLayout_7.addWidget(self.progressBar_5)
        self.pushButtonB_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButtonB_5.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButtonB_5.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButtonB_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonB_5.setAutoFillBackground(False)
        self.pushButtonB_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.pushButtonB_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../prefs/icons/UI/folder-blue-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonB_5.setIcon(icon)
        self.pushButtonB_5.setIconSize(QtCore.QSize(60, 60))
        self.pushButtonB_5.setAutoExclusive(False)
        self.pushButtonB_5.setAutoDefault(False)
        self.pushButtonB_5.setDefault(False)
        self.pushButtonB_5.setFlat(True)
        self.pushButtonB_5.setObjectName("pushButtonB_5")
        self.verticalLayout_7.addWidget(self.pushButtonB_5)
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_23.setMinimumSize(QtCore.QSize(50, 0))
        self.label_23.setMaximumSize(QtCore.QSize(50, 60))
        self.label_23.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.jobCardLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setContentsMargins(1, 3, 1, 3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.progressBar_6 = QtWidgets.QProgressBar(self.horizontalLayoutWidget_6)
        self.progressBar_6.setMaximumSize(QtCore.QSize(60, 10))
        self.progressBar_6.setProperty("value", 24)
        self.progressBar_6.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.progressBar_6.setObjectName("progressBar_6")
        self.verticalLayout_8.addWidget(self.progressBar_6)
        self.pushButtonB_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButtonB_6.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButtonB_6.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButtonB_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonB_6.setAutoFillBackground(False)
        self.pushButtonB_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.pushButtonB_6.setText("")
        self.pushButtonB_6.setIcon(icon)
        self.pushButtonB_6.setIconSize(QtCore.QSize(60, 60))
        self.pushButtonB_6.setAutoExclusive(False)
        self.pushButtonB_6.setAutoDefault(False)
        self.pushButtonB_6.setDefault(False)
        self.pushButtonB_6.setFlat(True)
        self.pushButtonB_6.setObjectName("pushButtonB_6")
        self.verticalLayout_8.addWidget(self.pushButtonB_6)
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_24.setMinimumSize(QtCore.QSize(50, 0))
        self.label_24.setMaximumSize(QtCore.QSize(50, 60))
        self.label_24.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_8.addWidget(self.label_24)
        self.jobCardLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(1)
        self.verticalLayout_9.setContentsMargins(1, 3, 1, 3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.progressBar_7 = QtWidgets.QProgressBar(self.horizontalLayoutWidget_6)
        self.progressBar_7.setMaximumSize(QtCore.QSize(60, 10))
        self.progressBar_7.setProperty("value", 24)
        self.progressBar_7.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.progressBar_7.setObjectName("progressBar_7")
        self.verticalLayout_9.addWidget(self.progressBar_7)
        self.pushButtonB_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButtonB_7.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButtonB_7.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButtonB_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonB_7.setAutoFillBackground(False)
        self.pushButtonB_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.pushButtonB_7.setText("")
        self.pushButtonB_7.setIcon(icon)
        self.pushButtonB_7.setIconSize(QtCore.QSize(60, 60))
        self.pushButtonB_7.setAutoExclusive(False)
        self.pushButtonB_7.setAutoDefault(False)
        self.pushButtonB_7.setDefault(False)
        self.pushButtonB_7.setFlat(True)
        self.pushButtonB_7.setObjectName("pushButtonB_7")
        self.verticalLayout_9.addWidget(self.pushButtonB_7)
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_25.setMinimumSize(QtCore.QSize(50, 0))
        self.label_25.setMaximumSize(QtCore.QSize(50, 60))
        self.label_25.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_9.addWidget(self.label_25)
        self.jobCardLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(1)
        self.verticalLayout_10.setContentsMargins(1, 3, 1, 3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.progressBar_8 = QtWidgets.QProgressBar(self.horizontalLayoutWidget_6)
        self.progressBar_8.setMaximumSize(QtCore.QSize(60, 10))
        self.progressBar_8.setProperty("value", 24)
        self.progressBar_8.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.progressBar_8.setObjectName("progressBar_8")
        self.verticalLayout_10.addWidget(self.progressBar_8)
        self.pushButtonB_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButtonB_8.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButtonB_8.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButtonB_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonB_8.setAutoFillBackground(False)
        self.pushButtonB_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.pushButtonB_8.setText("")
        self.pushButtonB_8.setIcon(icon)
        self.pushButtonB_8.setIconSize(QtCore.QSize(60, 60))
        self.pushButtonB_8.setAutoExclusive(False)
        self.pushButtonB_8.setAutoDefault(False)
        self.pushButtonB_8.setDefault(False)
        self.pushButtonB_8.setFlat(True)
        self.pushButtonB_8.setObjectName("pushButtonB_8")
        self.verticalLayout_10.addWidget(self.pushButtonB_8)
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_26.setMinimumSize(QtCore.QSize(50, 0))
        self.label_26.setMaximumSize(QtCore.QSize(50, 60))
        self.label_26.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_10.addWidget(self.label_26)
        self.jobCardLayout.addLayout(self.verticalLayout_10)
        self.NameCardWidget = QtWidgets.QWidget(self.centralwidget)
        self.NameCardWidget.setGeometry(QtCore.QRect(20, 20, 270, 100))
        self.NameCardWidget.setMinimumSize(QtCore.QSize(270, 100))
        self.NameCardWidget.setMaximumSize(QtCore.QSize(270, 100))
        self.NameCardWidget.setObjectName("NameCardWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.NameCardWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 271, 92))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.NameCardLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.NameCardLayout.setSpacing(1)
        self.NameCardLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.NameCardLayout.setContentsMargins(3, 1, 3, 1)
        self.NameCardLayout.setObjectName("NameCardLayout")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(90, 90))
        self.label_10.setMaximumSize(QtCore.QSize(90, 90))
        self.label_10.setAutoFillBackground(False)
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../prefs/icons/UI/cat-alt-256.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.NameCardLayout.addWidget(self.label_10)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 60))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setMaximumSize(QtCore.QSize(120, 60))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(80, 0))
        self.label_6.setMaximumSize(QtCore.QSize(80, 60))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        self.label_7.setMaximumSize(QtCore.QSize(120, 60))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(80, 0))
        self.label_8.setMaximumSize(QtCore.QSize(80, 60))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(120, 0))
        self.label_9.setMaximumSize(QtCore.QSize(120, 60))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_4.setMaximumSize(QtCore.QSize(80, 60))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setMaximumSize(QtCore.QSize(120, 60))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.NameCardLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "User Name:  ", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "User Name:  ", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "User Name:  ", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "User Name:  ", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "User Name:  ", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "AAAAAAAAAA", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Departement:  ", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "BBBBBBB", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Section:  ", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "BBBBBBB", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Special:  ", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "BBBBBBB", None, -1))




class mod_MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
   
    def __init__(self, parent= QtWidgets.QApplication.activeWindow()):
        super(mod_MainWindow, self).__init__(parent)
        #self.QTITEM.ACTION.connect(self.MODDEF)
        self.setupUi(self)
    #def self.MODDEF(self):



def main():
    global ui
    app = QtWidgets.QApplication.instance()
    if app == None: app = QtWidgets.QApplication(sys.argv)
    try:
        ui.close()
        ui.deleteLater()
    except: pass
    ui = mod_MainWindow()
    ui.show()
 
if __name__ == '__main__':
    main()


 